version: '3.9'

services:

  app:
    build: .
    container_name: learnforward_app
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:9000"
    volumes:
      - storage:/var/www/html/storage
    depends_on:
      - mysql
    networks:
      - learnforward

  mysql:
    image: mysql:8.0
    container_name: learnforward_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - learnforward

  worker:
    build: .
    container_name: learnforward_worker
    restart: unless-stopped
    command: php artisan queue:work redis --sleep=3 --tries=3 --queue=default,completions
    env_file: .env
    volumes:
      - storage:/var/www/html/storage
    depends_on:
      - mysql
    networks:
      - learnforward

volumes:
  mysql_data:
  storage:

networks:
  learnforward:
    driver: bridge